const admin = require('firebase-admin')
const { getEnvFunctions } = require('../envFunctionsHelper')

/**
 * Get the correct base URL based on environment
 * @returns {string} Base URL for the current environment
 */
function getBaseUrl() {
    if (process.env.FUNCTIONS_EMULATOR) {
        return 'http://localhost:5000'
    }

    // Determine project ID from environment
    let projectId = process.env.GCLOUD_PROJECT || process.env.GCP_PROJECT
    if (!projectId) {
        try {
            const cfg = process.env.FIREBASE_CONFIG ? JSON.parse(process.env.FIREBASE_CONFIG) : null
            if (cfg && cfg.projectId) projectId = cfg.projectId
        } catch (_) {}
    }
    if (!projectId) {
        try {
            projectId = (admin.app() && admin.app().options && admin.app().options.projectId) || undefined
        } catch (_) {}
    }

    if (projectId === 'alldonealeph') {
        return 'https://my.alldone.app'
    }
    if (projectId === 'alldonestaging') {
        return 'https://mystaging.alldone.app'
    }

    return 'https://my.alldone.app'
}

// Emoji detection helpers to keep WhatsApp content within safe limits
const EMOJI_CODEPOINT_RANGES = [
    [0x1f300, 0x1f5ff],
    [0x1f600, 0x1f64f],
    [0x1f680, 0x1f6ff],
    [0x1f700, 0x1f77f],
    [0x1f780, 0x1f7ff],
    [0x1f800, 0x1f8ff],
    [0x1f900, 0x1f9ff],
    [0x1fa00, 0x1faff],
    [0x2600, 0x26ff],
    [0x2700, 0x27bf],
]

const VARIATION_SELECTOR_CODEPOINT = 0xfe0f
const ZERO_WIDTH_JOINER_CODEPOINT = 0x200d
const SKIN_TONE_CODEPOINT_RANGE = [0x1f3fb, 0x1f3ff]

function isEmojiCodePoint(codePoint) {
    if (!codePoint) return false
    if (codePoint === VARIATION_SELECTOR_CODEPOINT) return false
    if (codePoint === ZERO_WIDTH_JOINER_CODEPOINT) return false
    if (codePoint >= SKIN_TONE_CODEPOINT_RANGE[0] && codePoint <= SKIN_TONE_CODEPOINT_RANGE[1]) {
        return false
    }

    return EMOJI_CODEPOINT_RANGES.some(([start, end]) => codePoint >= start && codePoint <= end)
}

function countEmojiCharacters(value) {
    const chars = Array.from(value || '')
    let count = 0

    for (let i = 0; i < chars.length; i++) {
        const codePoint = chars[i].codePointAt(0)
        if (!codePoint) continue

        // Flag emojis are made from pairs of regional indicator symbols – count them once
        if (codePoint >= 0x1f1e6 && codePoint <= 0x1f1ff) {
            const nextCodePoint = chars[i + 1]?.codePointAt(0)
            if (nextCodePoint >= 0x1f1e6 && nextCodePoint <= 0x1f1ff) {
                count += 1
                i += 1
                continue
            }
        }

        if (isEmojiCodePoint(codePoint)) {
            count += 1
        }
    }

    return count
}

/**
 * Service for sending WhatsApp messages using Twilio API
 */
class TwilioWhatsAppService {
    constructor() {
        // Load environment variables using our unified helper
        const envFunctions = getEnvFunctions()

        this.twilioAccountSid = envFunctions.TWILIO_ACCOUNT_SID
        this.twilioAuthToken = envFunctions.TWILIO_AUTH_TOKEN
        this.twilioWhatsAppFrom = envFunctions.TWILIO_WHATSAPP_FROM || 'whatsapp:+14155238886'

        // Initialize Twilio client lazily
        this.client = null
    }

    /**
     * Initialize Twilio client
     * @private
     */
    _initializeTwilioClient() {
        if (!this.client) {
            if (!this.twilioAccountSid || !this.twilioAuthToken) {
                throw new Error(
                    'Twilio credentials not configured. Please set TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN environment variables.'
                )
            }

            const twilio = require('twilio')
            this.client = twilio(this.twilioAccountSid, this.twilioAuthToken)
        }
        return this.client
    }

    /**
     * Format phone number for WhatsApp (must include country code and whatsapp: prefix)
     * @param {string} phoneNumber - Phone number to format
     * @returns {string} - Formatted WhatsApp phone number
     * @private
     */
    _formatWhatsAppNumber(phoneNumber) {
        if (!phoneNumber) {
            throw new Error('Phone number is required')
        }

        // Remove any existing whatsapp: prefix
        let cleanNumber = phoneNumber.replace(/^whatsapp:/, '')

        // Remove all non-numeric characters except +
        cleanNumber = cleanNumber.replace(/[^\d+]/g, '')

        // Add + if not present and number doesn't start with it
        if (!cleanNumber.startsWith('+')) {
            cleanNumber = '+' + cleanNumber
        }

        // Add whatsapp: prefix
        return `whatsapp:${cleanNumber}`
    }

    /**
     * Prepare and validate WhatsApp template variables against common policy violations
     * @param {string} taskResult - Raw task result generated by the assistant
     * @returns {{ value: string, adjustments: string[], blockingIssues: string[], isValid: boolean }}
     * @private
     */
    _prepareTaskResultForTemplate(taskResult) {
        const adjustments = []
        const blockingIssues = []

        // Normalise the incoming value to a string
        let value = ''
        if (typeof taskResult === 'string') {
            value = taskResult
        } else if (taskResult === null || taskResult === undefined) {
            value = ''
        } else {
            value = String(taskResult)
            adjustments.push('Coerced non-string task result into string representation.')
        }

        // Normalise line endings for consistent processing
        value = value.replace(/\r\n?/g, '\n')

        if (!value.trim()) {
            value = 'Task completed successfully'
            adjustments.push('Replaced empty task result with default fallback message.')
        }

        if (/\n\s*\n/.test(value)) {
            value = value.replace(/\n\s*\n+/g, '\n')
            adjustments.push('Collapsed blank lines (including whitespace-only lines) to a single newline.')
        }

        if (value.length > 300) {
            value = value.slice(0, 300) + '...'
            adjustments.push('Truncated task result to 300 characters to satisfy WhatsApp template limits.')
        }

        if (/[ \t]{5,}/.test(value)) {
            value = value.replace(/[ \t]{5,}/g, '    ')
            adjustments.push('Collapsed sequences of more than four consecutive whitespace characters.')
        }

        const lines = value.split('\n')
        let removedLeadingWhitespace = false
        const normalisedLines = lines.map(line => {
            const trimmedLine = line.replace(/^\s+/, '')
            if (trimmedLine.length !== line.length) {
                removedLeadingWhitespace = true
            }
            return trimmedLine
        })

        if (removedLeadingWhitespace) {
            adjustments.push('Removed leading whitespace from lines to prevent leading spaces after newlines.')
        }

        value = normalisedLines.join('\n').trim()

        // Replace common Unicode punctuation with ASCII-safe equivalents
        // This reduces chances of Content Variables rejection due to unsupported punctuation
        const PUNCTUATION_MAP = {
            '\u2018': "'", // left single quotation mark
            '\u2019': "'", // right single quotation mark / apostrophe
            '\u201A': ',', // single low-9 quotation mark
            '\u201B': "'", // single high-reversed-9 quotation mark
            '\u201C': '"', // left double quotation mark
            '\u201D': '"', // right double quotation mark
            '\u201E': '"', // double low-9 quotation mark
            '\u2013': '-', // en dash
            '\u2014': '-', // em dash
            '\u2015': '-', // horizontal bar
            '\u2026': '...', // ellipsis
            '\u2212': '-', // minus sign
            '\u00A0': ' ', // no-break space
            '\u202F': ' ', // narrow no-break space
            '\u2009': ' ', // thin space
            '\u200A': ' ', // hair space
            '\u200B': '', // zero-width space
            '\u2060': '', // word joiner
        }
        value = value.replace(
            /[\u2018\u2019\u201A\u201B\u201C\u201D\u201E\u2013\u2014\u2015\u2026\u2212\u00A0\u202F\u2009\u200A\u200B\u2060]/g,
            ch => PUNCTUATION_MAP[ch] || ''
        )

        if (!value.trim()) {
            blockingIssues.push('Prepared WhatsApp content is empty after sanitisation.')
        }

        if (/[ \t]{5,}/.test(value)) {
            blockingIssues.push('WhatsApp content still contains more than four consecutive whitespace characters.')
        }

        if (/\n\s*\n/.test(value)) {
            blockingIssues.push('WhatsApp content contains consecutive newline characters.')
        }

        if (/\n\s/.test(value)) {
            blockingIssues.push('WhatsApp content has leading whitespace immediately after a newline.')
        }

        const emojiCount = countEmojiCharacters(value)
        if (emojiCount > 10) {
            blockingIssues.push(
                `WhatsApp content contains more than 10 emoji characters, exceeding safe limits (found ${emojiCount}).`
            )
        }

        // Do not pre-escape newlines here; JSON.stringify will escape them once.

        return {
            value,
            adjustments,
            blockingIssues,
            isValid: blockingIssues.length === 0,
        }
    }

    /**
     * Count total open tasks across all user's projects
     * @param {string} userId - User ID
     * @returns {Promise<number>} - Total count of open tasks
     * @private
     */
    async _countUserOpenTasks(userId) {
        try {
            const admin = require('firebase-admin')
            const moment = require('moment')
            const { ProjectService } = require('../shared/ProjectService')
            const { FEED_PUBLIC_FOR_ALL } = require('../Utils/HelperFunctionsCloud')

            const projectService = new ProjectService({
                database: admin.firestore(),
            })

            // Get user's active projects (excluding archived/template/guide)
            const projects = await projectService.getUserProjects(userId, {
                includeArchived: false,
                includeCommunity: false,
                activeOnly: true,
            })

            if (projects.length === 0) {
                return 0
            }

            // Get user data to check if anonymous and build visibility filter
            const userDoc = await admin.firestore().doc(`users/${userId}`).get()
            const isAnonymous = userDoc.exists ? userDoc.data().isAnonymous : false
            const allowUserIds = isAnonymous ? [FEED_PUBLIC_FOR_ALL] : [FEED_PUBLIC_FOR_ALL, userId]

            const dateEndToday = moment().endOf('day').valueOf()
            let totalCount = 0

            console.log('WhatsApp: Counting open tasks for user:', {
                userId,
                projectsCount: projects.length,
                dateEndToday,
                dateEndTodayFormatted: moment(dateEndToday).format('YYYY-MM-DD HH:mm:ss'),
                allowUserIds,
                isAnonymous,
            })

            // Query tasks across all projects
            for (const project of projects) {
                const projectId = project.id

                // Count tasks where user is currentReviewerId
                const reviewerTasksSnapshot = await admin
                    .firestore()
                    .collection(`items/${projectId}/tasks`)
                    .where('inDone', '==', false)
                    .where('parentId', '==', null)
                    .where('currentReviewerId', '==', userId)
                    .where('dueDate', '<=', dateEndToday)
                    .where('isPublicFor', 'array-contains-any', allowUserIds)
                    .get()

                const reviewerCount = reviewerTasksSnapshot.docs.length
                console.log('WhatsApp: Reviewer tasks in project:', {
                    projectId,
                    projectName: project.name,
                    count: reviewerCount,
                })

                totalCount += reviewerCount

                // Count tasks where user is in observersIds
                // Note: Cannot add isPublicFor filter here because Firestore only allows one array operation per query
                const observedTasksSnapshot = await admin
                    .firestore()
                    .collection(`items/${projectId}/tasks`)
                    .where('inDone', '==', false)
                    .where('parentId', '==', null)
                    .where('observersIds', 'array-contains', userId)
                    .get()

                // Filter observed tasks by dueDateByObserversIds and isPublicFor
                let observedCount = 0
                observedTasksSnapshot.docs.forEach(doc => {
                    const data = doc.data()
                    const dueDateByObserversIds = data.dueDateByObserversIds || {}
                    const isPublicFor = data.isPublicFor || []

                    // Check visibility permissions
                    const isVisible = allowUserIds.some(allowedId => isPublicFor.includes(allowedId))

                    if (isVisible && dueDateByObserversIds[userId] && dueDateByObserversIds[userId] <= dateEndToday) {
                        totalCount++
                        observedCount++
                    }
                })

                console.log('WhatsApp: Observed tasks in project:', {
                    projectId,
                    projectName: project.name,
                    totalDocs: observedTasksSnapshot.docs.length,
                    countedAfterFilter: observedCount,
                })
            }

            console.log('WhatsApp: Final open tasks count:', {
                userId,
                totalCount,
            })

            return totalCount
        } catch (error) {
            console.error('Error counting user open tasks:', {
                error: error.message,
                userId,
                stack: error.stack,
            })
            // Return 0 on error to avoid blocking the notification
            return 0
        }
    }

    /**
     * Send WhatsApp message
     * @param {string} to - Recipient phone number
     * @param {string} message - Message content
     * @returns {Promise<Object>} - Twilio message response
     */
    async sendWhatsAppMessage(to, message) {
        try {
            const client = this._initializeTwilioClient()
            const formattedTo = this._formatWhatsAppNumber(to)

            console.log('Sending WhatsApp message:', {
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
                messageLength: message.length,
                timestamp: new Date().toISOString(),
            })

            const response = await client.messages.create({
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
                body: message,
            })

            console.log('WhatsApp message sent successfully:', {
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                timestamp: new Date().toISOString(),
            })

            return {
                success: true,
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                message: 'WhatsApp message sent successfully',
            }
        } catch (error) {
            console.error('Failed to send WhatsApp message:', {
                error: error.message,
                code: error.code,
                status: error.status,
                to,
                timestamp: new Date().toISOString(),
                stack: error.stack,
            })

            return {
                success: false,
                error: error.message,
                code: error.code,
                status: error.status,
                to,
                message: 'Failed to send WhatsApp message',
            }
        }
    }

    /**
     * Send task completion notification via WhatsApp using Content Template
     * @param {string} userPhone - User's phone number
     * @param {string} userId - User ID (for counting open tasks)
     * @param {string} projectId - Project ID
     * @param {string} taskId - Task ID
     * @param {string} assistantName - Assistant display name
     * @param {Object} taskData - Task information
     * @param {string} taskResult - AI-generated task result
     * @returns {Promise<Object>} - Send result
     */
    async sendTaskCompletionNotification(
        userPhone,
        userId,
        projectId,
        taskId,
        assistantName,
        taskData,
        taskResult = ''
    ) {
        if (!userPhone) {
            console.warn('No phone number provided for WhatsApp notification')
            return {
                success: false,
                error: 'No phone number provided',
                message: 'User phone number is required for WhatsApp notifications',
            }
        }

        try {
            const client = this._initializeTwilioClient()
            const formattedTo = this._formatWhatsAppNumber(userPhone)

            const preparedContent = this._prepareTaskResultForTemplate(taskResult)

            if (!preparedContent.isValid) {
                console.warn('WhatsApp content validation failed; aborting send.', {
                    issues: preparedContent.blockingIssues,
                    userPhone: formattedTo,
                    taskName: taskData?.name,
                })

                return {
                    success: false,
                    error: 'WhatsApp content did not pass validation',
                    issues: preparedContent.blockingIssues,
                    to: formattedTo,
                    message: 'WhatsApp message blocked due to policy validation errors',
                }
            }

            if (preparedContent.adjustments.length) {
                console.log('Applied WhatsApp content normalisation prior to send.', {
                    adjustments: preparedContent.adjustments,
                    userPhone: formattedTo,
                    taskName: taskData?.name,
                })
            }

            // Human-friendly, single-line preview for logs (shows literal \n)
            const previewSingleLine = preparedContent.value.replace(/\n/g, '\\n')
            console.log('WhatsApp content preview (single line):', {
                length: preparedContent.value.length,
                preview: previewSingleLine,
            })

            // Content variables for the template
            // {{1}}: Assistant Name
            const assistantDisplayName = assistantName || 'Assistant'

            // {{2}}: Project Name
            let projectName = 'Project'
            try {
                const projectDoc = await admin.firestore().collection('projects').doc(projectId).get()
                if (projectDoc.exists) {
                    projectName = projectDoc.data().name || 'Project'
                }
            } catch (error) {
                console.error('Error fetching project name:', error.message)
            }

            // {{3}}: Topic/Task Name
            let topicName = 'Task'
            try {
                // First try to get from taskData
                if (taskData && taskData.name) {
                    topicName = taskData.name
                } else {
                    // Fetch from Firestore if not in taskData
                    const taskDoc = await admin.firestore().doc(`items/${projectId}/tasks/${taskId}`).get()
                    if (taskDoc.exists) {
                        topicName = taskDoc.data().name || 'Task'
                    }
                }
            } catch (error) {
                console.error('Error fetching task name:', error.message)
            }

            // {{4}}: AI Task result - flatten newlines to spaces to satisfy stricter template constraints
            const templateValue = preparedContent.value
                .replace(/\n/g, ' ')
                .replace(/\s{2,}/g, ' ')
                .trim()
            console.log('WhatsApp template value metrics:', {
                originalLength: preparedContent.value.length,
                templateLength: templateValue.length,
            })

            // {{5}}: Conversation Link
            const baseUrl = getBaseUrl()
            const conversationUrl = `${baseUrl}/projects/${projectId}/tasks/${taskId}/chat`

            // {{6}}: Total open tasks count across all projects
            const openTasksCount = await this._countUserOpenTasks(userId)

            const contentVariables = JSON.stringify({
                1: assistantDisplayName,
                2: projectName,
                3: topicName,
                4: templateValue,
                5: conversationUrl,
                6: openTasksCount.toString(),
            })

            console.log('Sending WhatsApp message with Content Template:', {
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
                contentSid: 'HX627be85ad459e8748030b035ae231e8a',
                contentVariables,
                assistantName: assistantDisplayName,
                projectName,
                topicName,
                openTasksCount,
                conversationUrl,
                timestamp: new Date().toISOString(),
            })

            const response = await client.messages.create({
                contentSid: 'HX627be85ad459e8748030b035ae231e8a',
                contentVariables,
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
            })

            console.log('WhatsApp message sent successfully with template:', {
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                timestamp: new Date().toISOString(),
            })

            return {
                success: true,
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                message: 'WhatsApp message sent successfully using content template',
            }
        } catch (error) {
            console.error('Failed to send WhatsApp message with template:', {
                error: error.message,
                code: error.code,
                status: error.status,
                userPhone,
                taskName: taskData?.name,
                timestamp: new Date().toISOString(),
                stack: error.stack,
            })

            return {
                success: false,
                error: error.message,
                code: error.code,
                status: error.status,
                to: userPhone,
                message: 'Failed to send WhatsApp message with content template',
            }
        }
    }

    /**
     * Send a generic notification via WhatsApp using Content Template
     * Maps to template variables as:
     * 1: Alldone.app
     * 2: Project name
     * 3: Object name
     * 4: Update text (sanitized)
     * 5: Object link (absolute URL)
     * 6: Number of open/overdue tasks
     * @param {string} userPhone
     * @param {string} userId
     * @param {string} projectName
     * @param {string} objectName
     * @param {string} updateText
     * @param {string} objectUrl
     * @returns {Promise<Object>}
     */
    async sendNotificationWithTemplate(
        userPhone,
        userId,
        projectName,
        objectName,
        updateText,
        objectUrl,
        assistantName,
        openTasksCountOverride
    ) {
        if (!userPhone) {
            console.warn('No phone number provided for WhatsApp notification')
            return { success: false, error: 'No phone number provided', to: userPhone }
        }

        try {
            const client = this._initializeTwilioClient()
            const formattedTo = this._formatWhatsAppNumber(userPhone)

            const preparedContent = this._prepareTaskResultForTemplate(updateText)
            if (!preparedContent.isValid) {
                console.warn('WhatsApp content validation failed; aborting send (generic).', {
                    issues: preparedContent.blockingIssues,
                    userPhone: formattedTo,
                    objectName,
                })
                return {
                    success: false,
                    error: 'WhatsApp content did not pass validation',
                    issues: preparedContent.blockingIssues,
                    to: formattedTo,
                }
            }

            if (preparedContent.adjustments.length) {
                console.log('Applied WhatsApp content normalisation prior to send (generic).', {
                    adjustments: preparedContent.adjustments,
                    userPhone: formattedTo,
                    objectName,
                })
            }

            // Flatten newlines for stricter template constraints
            const templateValue = preparedContent.value
                .replace(/\n/g, ' ')
                .replace(/\s{2,}/g, ' ')
                .trim()

            // Count open/overdue tasks across all projects for this user
            let openTasksCountString = '0'
            if (openTasksCountOverride !== undefined && openTasksCountOverride !== null) {
                openTasksCountString = openTasksCountOverride.toString()
            } else {
                const openTasksCount = await this._countUserOpenTasks(userId)
                openTasksCountString = openTasksCount.toString()
            }

            const contentVariables = JSON.stringify({
                1: assistantName || 'Alldone.app',
                2: projectName || 'Project',
                3: objectName || 'Item',
                4: templateValue,
                5: objectUrl || getBaseUrl(),
                6: openTasksCountString,
            })

            console.log('Sending WhatsApp generic template:', {
                to: formattedTo,
                contentSid: 'HX627be85ad459e8748030b035ae231e8a',
                contentVariables,
            })

            const response = await client.messages.create({
                contentSid: 'HX627be85ad459e8748030b035ae231e8a',
                contentVariables,
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
            })

            console.log('WhatsApp message sent successfully (generic):', {
                sid: response.sid,
                status: response.status,
                to: formattedTo,
            })

            return {
                success: true,
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                message: 'WhatsApp message sent successfully using content template',
            }
        } catch (error) {
            console.error('Failed to send WhatsApp message with template (generic):', {
                error: error.message,
                code: error.code,
                status: error.status,
                userPhone,
                stack: error.stack,
            })
            return {
                success: false,
                error: error.message,
                code: error.code,
                status: error.status,
                to: userPhone,
                message: 'Failed to send WhatsApp message with content template',
            }
        }
    }

    /**
     * Test WhatsApp configuration
     * @param {string} testPhoneNumber - Phone number to send test message to
     * @returns {Promise<Object>} - Test result
     */
    async testConfiguration(testPhoneNumber) {
        const testMessage = `🧪 *Alldone WhatsApp Test*

This is a test message to verify your WhatsApp integration is working correctly.

✅ Configuration is successful!
🕒 ${new Date().toISOString()}

Powered by Alldone Assistant 🚀`

        return await this.sendWhatsAppMessage(testPhoneNumber, testMessage)
    }

    /**
     * Send a welcome notification via WhatsApp using a template with no variables.
     * Used when a new user adds their WhatsApp number.
     * @param {string} userPhone - User's phone number
     * @returns {Promise<Object>} - Send result
     */
    async sendWelcomeNotification(userPhone) {
        if (!userPhone) {
            console.warn('No phone number provided for WhatsApp welcome notification')
            return { success: false, error: 'No phone number provided', to: userPhone }
        }

        try {
            const client = this._initializeTwilioClient()
            const formattedTo = this._formatWhatsAppNumber(userPhone)

            console.log('Sending WhatsApp welcome template:', {
                to: formattedTo,
                contentSid: 'HXa3f62b884796b66c390aaf2b336dbcd7',
            })

            const response = await client.messages.create({
                contentSid: 'HXa3f62b884796b66c390aaf2b336dbcd7',
                from: this.twilioWhatsAppFrom,
                to: formattedTo,
            })

            console.log('WhatsApp welcome message sent successfully:', {
                sid: response.sid,
                status: response.status,
                to: formattedTo,
            })

            return {
                success: true,
                sid: response.sid,
                status: response.status,
                to: formattedTo,
                message: 'WhatsApp welcome message sent successfully',
            }
        } catch (error) {
            console.error('Failed to send WhatsApp welcome message:', {
                error: error.message,
                code: error.code,
                status: error.status,
                userPhone,
                stack: error.stack,
            })
            return {
                success: false,
                error: error.message,
                code: error.code,
                status: error.status,
                to: userPhone,
                message: 'Failed to send WhatsApp welcome message',
            }
        }
    }
}

module.exports = TwilioWhatsAppService
