const FOLLOWED_TAB = 0
const ALL_TAB = 1
const BOTH_TABS = 2

const MAX_AMOUNT_OF_FEEDS_STORED = 200

const FEED_TASK_CREATED = 9
const FEED_TASK_DUE_DATE_CHANGED = 13
const FEED_TASK_ASSIGNEE_ESTIMATION_CHANGED = 15
const FEED_TASK_RECURRENCE_CHANGED = 16
const FEED_TASK_HIGHLIGHTED_CHANGED = 20
const FEED_TASK_REVIEWER_ESTIMATION_CHANGED = 22
const FEED_TASK_FOLLOWED = 27
const FEED_TASK_PRIVACY_CHANGED = 19
const FEED_TASK_DESCRIPTION = 577
const FEED_TASK_PARENT_GOAL = 578
const FEED_TASK_ALERT_CHANGED = 579
const FEED_TASK_SOMEDAY_SELECTED = 580
const FEED_TASK_UPDATED = 'FEED_TASK_UPDATED'

const FEED_CONTACT_ADDED = 41
const FEED_CONTACT_EMAIL_CHANGED = 43
const FEED_CONTACT_PHONE_NUMBER_CHANGED = 44
const FEED_CONTACT_PRIVACY_CHANGED = 45
const FEED_CONTACT_ROLE_CHANGED = 46
const FEED_CONTACT_COMPANY_CHANGED = 48
const FEED_CONTACT_FOLLOWED = 52
const FEED_CONTACT_DESCRIPTION_CHANGED = 531
const FEED_CONTACT_HIGHLIGHT_CHANGED = 573

const FEED_NOTE_CREATED = 63
const FEED_NOTE_FOLLOWED = 65
const FEED_NOTE_TITLE_CHANGED = 68
const FEED_NOTE_HIGHLIGHTED_CHANGED = 69
const FEED_NOTE_PRIVACY_CHANGED = 70
const FEED_NOTE_OWNER_CHANGED = 71
const FEED_NOTE_STICKY = 75
const FEED_NOTE_UPDATED = 'FEED_NOTE_UPDATED'

const FEED_GOAL_CREATED = 80
const FEED_GOAL_ASSIGNEES_CHANGED = 84
const FEED_GOAL_FOLLOWED = 88
const FEED_GOAL_HIGHLIGHTED_CHANGED = 91
const FEED_GOAL_CAPACITY_CHANGED = 92
const FEED_GOAL_DESCRIPTION_CHANGED = 93
const FEED_GOAL_PRIVACY_CHANGED = 95

const FEED_ASSISTANT_CREATED = 'FEED_ASSISTANT_CREATED'
const FEED_ASSISTANT_DESCRIPTION_CHANGED = 'FEED_ASSISTANT_DESCRIPTION_CHANGED'
const FEED_ASSISTANT_FOLLOWED = 'FEED_ASSISTANT_FOLLOWED'

module.exports = {
    MAX_AMOUNT_OF_FEEDS_STORED,
    FOLLOWED_TAB,
    ALL_TAB,
    BOTH_TABS,
    FEED_TASK_CREATED,
    FEED_TASK_FOLLOWED,
    FEED_TASK_PRIVACY_CHANGED,
    FEED_TASK_DESCRIPTION,
    FEED_TASK_DUE_DATE_CHANGED,
    FEED_TASK_PARENT_GOAL,
    FEED_TASK_ALERT_CHANGED,
    FEED_TASK_SOMEDAY_SELECTED,
    FEED_TASK_UPDATED,
    FEED_TASK_HIGHLIGHTED_CHANGED,
    FEED_TASK_RECURRENCE_CHANGED,
    FEED_TASK_ASSIGNEE_ESTIMATION_CHANGED,
    FEED_TASK_REVIEWER_ESTIMATION_CHANGED,
    FEED_GOAL_CREATED,
    FEED_GOAL_FOLLOWED,
    FEED_GOAL_ASSIGNEES_CHANGED,
    FEED_GOAL_HIGHLIGHTED_CHANGED,
    FEED_GOAL_DESCRIPTION_CHANGED,
    FEED_GOAL_PRIVACY_CHANGED,
    FEED_GOAL_CAPACITY_CHANGED,
    FEED_CONTACT_ADDED,
    FEED_CONTACT_FOLLOWED,
    FEED_CONTACT_PRIVACY_CHANGED,
    FEED_CONTACT_COMPANY_CHANGED,
    FEED_CONTACT_ROLE_CHANGED,
    FEED_CONTACT_DESCRIPTION_CHANGED,
    FEED_CONTACT_HIGHLIGHT_CHANGED,
    FEED_CONTACT_PHONE_NUMBER_CHANGED,
    FEED_CONTACT_EMAIL_CHANGED,
    FEED_NOTE_CREATED,
    FEED_NOTE_FOLLOWED,
    FEED_NOTE_PRIVACY_CHANGED,
    FEED_NOTE_HIGHLIGHTED_CHANGED,
    FEED_NOTE_STICKY,
    FEED_NOTE_TITLE_CHANGED,
    FEED_NOTE_OWNER_CHANGED,
    FEED_NOTE_UPDATED,
    FEED_ASSISTANT_CREATED,
    FEED_ASSISTANT_FOLLOWED,
    FEED_ASSISTANT_DESCRIPTION_CHANGED,
}
