export const ProjectsByUserId = [
    {
        index: 0,
        id: '-LcRVRo6mhbC0oXCcZ2F',
        color: '#39CCCC',
        name: 'Another one',
        tasksAmount: 6,
        tasks: [],
        tags: {
            TagTag: { date: 1571603092008, items: ['-Lreq05U8_OD6QVdSrVz'] },
            anothertag: {
                date: 1571601734603,
                items: ['-Lrekph1bkT6MO7qHk7e'],
            },
            followup: { date: 1572878416375, items: ['-Lsqqzb7IIWW7i0qJOXH'] },
            hashtag: { date: 1570479777796, items: ['-LqbsuUTQ2dopYrVXXxf'] },
            mynewtag: { date: 1571601712132, items: ['-LrekkCvkUQzjfiDGij4'] },
            newtagnewtag: {
                date: 1572206774487,
                items: ['-LsDosYeyFzk3L8XvkYG'],
            },
            review: {
                date: 1581860525690,
                items: [
                    '-LqbsmqVlorqbYB0H9vm',
                    '-LqbsigeJRgsFqCguAr7',
                    '-Lr5HtcTEfrRUmxc1LjM',
                    '-Lr5jvXfrzWyYvggA6HL',
                    '-Lr5jvXfrzWyYvggA6HL',
                    '-Lr5Mv9RbNcKy9x8vxk0',
                    '-LrenHTPUJGOemmSHC3z',
                    '-LrekkCvkUQzjfiDGij4',
                    '-Lreq05U8_OD6QVdSrVz',
                    '-Lrekph1bkT6MO7qHk7e',
                    '-LwjsQtYgP3L91gmSWB7',
                    '-LwjsSkynklTkgH7VYLW',
                    '-LwjsTlLPXyWRsIQXqPR',
                    '-LwjsUClPfJ-JTIrqsuL',
                    '-LwjsUb7UuZO-WBfdmU3',
                    '-LsE7O4mXpMWzkBApZMF',
                    '-LsmtzfYslpFzfMOehCI',
                    '-LsmuPypINgNQ0O7wmtT',
                    '-LsmuSHOfGN_tWytqdAW',
                    '-Lsn164QYvqLyidhU9Is',
                    '-Lsn18OvsnX10eQ-v7lF',
                    '-Lsn1L-wv6ObUJjggw8k',
                    '-Lsn21e9H2TVaOAX2OML',
                    '-Lsn27Y7xs4LjueCl__S',
                    '-Lsn2ScjnAsXd7YEl6QL',
                    '-Lsn6nj0El-FE5sbrC7Q',
                    '-LsnAJypfe00xZbb5-bZ',
                    '-LsnA_Jv67ocL4joBaIB',
                    '-LsnAuR444Gx16MW-RH-',
                    '-LsnBOosk3Eh29Xs-tpI',
                    '-LsnCdq3xMErwbmU7XiG',
                    '-LsnCq2tGvx92OpooYtL',
                    '-LsnCsczMcMBj6pmtMxX',
                    '-Lu1BTCYKRXQpvWb6vhp',
                    '-Lu1Btpb-mRVpJ6YB9fZ',
                    '-Lu1Co-DU0hqOUNE1vnW',
                    '-Lu1DsYPf7WIJVlKKF0w',
                    '-Lu1EMdBXwuDg6XoF-a-',
                    '-Lu1FXQTLx1P4Zah2VFG',
                    '-Lu1GKlIAYGsXHAzworX',
                    '-Lu1HJIkInlc5j_bU55m',
                    '-Lu1HZKqEldel0MTYtB0',
                    '-Lu1JU5KGqODc3XcS6in',
                    '-Lu1J__9tE9z8oZhgHMn',
                    '-Lu1Js3yCpmjZrSMd8tU',
                    '-Lu1K97sNeEdH8IBQsq_',
                    '-LsDosYeyFzk3L8XvkYG',
                    '-LxHZwq13pXCGGLUHirV',
                    '-LxHZxTVxScOGfColGZ9',
                    '-LxHZxuauC2rlLMwTFZ2',
                    '-LxHZyHlcWfwn_GjKOTV',
                    '-LxH_9lqCBuIGnwWi5T0',
                    '-LxH_Ukf3AfnfM7SEV_z',
                    '-LxH_V2VGXYyoVryq3DL',
                    '-LxHbyVVZH4CFDh_2Jwb',
                    '-LxHbzpXOcibD2mazGCZ',
                    '-LxH_V9FgOWKZmn0A1D2',
                    '-LsE919xXFyUoH6xD2SP',
                    '-LsmuPypINgNQ0O7wmtT',
                    '-LxH_9lqCBuIGnwWi5T0',
                    '-LxH_Ukf3AfnfM7SEV_z',
                    '-LyQw495vNdIR0eWj7dB',
                    '-LyQq5y_yA-xokREXM1e',
                    '-LyQnHVZTpwsvJkeytVm',
                    '-LxHc-V0bfK6J9WPqcc6',
                    '-LxHcu3IYyzYUAKkFBN2',
                    '-LxHePNDkkpoi5cOE69H',
                    '-LxHgmV08W98gztPlgFa',
                    '-LyQY4KycxV82MpBrdgN',
                    '-LyQvrhelpmXQAYTyewW',
                    '-LyQvxvckkEcg7EL5en1',
                    '-LyQvylkVZkLPfMfJeuc',
                    '-LyQvzUkddHRHIIk-iU2',
                    '-LyQw-9VLZ1yGA6fikX-',
                    '-LyQwGJS8UvROj8zncMM',
                    '-LyQwFXkgOhQo4kW1nNL',
                ],
            },
            rreview: { date: 1572212365808, items: ['-Lr5j2BWE5lNEXU-dZQk'] },
            test: { date: 1572212383994, items: ['-LmO_XwL_VvDAWfGDg0S'] },
            test2: { date: 1568589180796, items: ['-LorBqxZP4jBDyiP0f3x'] },
            test3: { date: 1568590903021, items: ['-LorIQQSGBck3pl9AcIg'] },
            wahnsinn: { date: 1576444469505 },
        },
        userIds: [
            'C08CK8x1I5YS2lxVixuLHaF3SrA3',
            'XVbBpdTHCfdo17bCqRrnGV85oJI2',
            's7jsNunUq6OQZttrrSyRO05MVFI2',
            'jsUAwtuUhfPrQwPFMtDyKAsdo7g1',
            'UUKU61Jc7ET8zE5ncN8F61HE19y1',
            'kTpVkeDAGMO7qIHvQ2uAbEUu0As1',
        ],
    },
    {
        index: 1,
        id: '-LmqhdoeMJC7zWWxK4Z-',
        color: '#FFFFFF',
        name: 'Private',
        tasksAmount: 6,
        tasks: [],
        tags: {
            hashtag: { date: 1568635366017, items: ['-LmqhvzwNDCPmSEWq012'] },
            hastag: { date: 1566770049081 },
            new: { date: 1572212303363, items: ['-LmypuE2ydjb0P_spm89'] },
            test: { date: 1566770042125 },
            testhash: { date: 1569185291595, items: ['-LpPimBM-m1O1vinhr3n'] },
        },
        userIds: ['UUKU61Jc7ET8zE5ncN8F61HE19y1'],
    },
]
