export const UsersByProjectId = [
    {
        id: 'C08CK8x1I5YS2lxVixuLHaF3SrA3',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
    {
        id: 'XVbBpdTHCfdo17bCqRrnGV85oJI2',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
    {
        id: 's7jsNunUq6OQZttrrSyRO05MVFI2',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
    {
        id: 'jsUAwtuUhfPrQwPFMtDyKAsdo7g1',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
    {
        id: 'UUKU61Jc7ET8zE5ncN8F61HE19y1',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
    {
        id: 'kTpVkeDAGMO7qIHvQ2uAbEUu0As1',
        done: false,
        name: '',
        userId: '',
        hasStar: false,
        created: 1555928430000,
        creatorId: '',
        dueDate: 1555928430000,
        completed: null,
        isPrivate: false,
        parentId: null,
        subtaskIds: [],
        subtaskNames: [],
        recurrence: { type: 'never' },
        inReview: null,
        toReview: null,
        lastChangeUserId: '',
    },
]
