export const OpenTasksViewInput = [
    [
        {
            id: '-LcRVT6MEWlqGQRkE2xw',
            done: false,
            name: 'My new task',
            userIds: ['C08CK8x1I5YS2lxVixuLHaF3SrA3'],
            hasStar: false,
            created: 1555192800000,
            creatorId: 'C08CK8x1I5YS2lxVixuLHaF3SrA3',
            dueDate: 1555273253219,
            completed: 1555273253219,
            isPrivate: false,
            parentId: null,
            subtaskIds: [],
            subtaskNames: [],
            recurrence: { type: 'never' },
            inReview: null,
            toReview: null,
        },
        {
            id: '-LcRZz0eNJkx7QZn_gti',
            done: false,
            name: 'later yo',
            userIds: ['C08CK8x1I5YS2lxVixuLHaF3SrA3'],
            hasStar: false,
            created: 1555192800000,
            creatorId: 'C08CK8x1I5YS2lxVixuLHaF3SrA3',
            dueDate: 1564735497020,
            completed: 1564735497020,
            isPrivate: false,
            parentId: null,
            subtaskIds: [],
            subtaskNames: [],
            recurrence: { type: 'never' },
            inReview: null,
            toReview: null,
        },
    ],
    [
        {
            id: '-LcRh9ABE_wbmsAhSUiN',
            done: false,
            name: 'test unknown yo',
            userIds: ['C08CK8x1I5YS2lxVixuLHaF3SrA3'],
            hasStar: false,
            created: 1555192800000,
            creatorId: 'C08CK8x1I5YS2lxVixuLHaF3SrA3',
            dueDate: 1555274088568,
            completed: 1555274088568,
            isPrivate: false,
            parentId: null,
            subtaskIds: [],
            subtaskNames: [],
            recurrence: { type: 'never' },
            inReview: null,
            toReview: null,
        },
    ],
]
