const FOLLOWER_TASKS_TYPE = 'tasks'
const FOLLOWER_GOALS_TYPE = 'goals'
const FOLLOWER_CONTACTS_TYPE = 'contacts'
const FOLLOWER_NOTES_TYPE = 'notes'
const FOLLOWER_ASSISTANTS_TYPE = 'assistants'

module.exports = {
    FOLLOWER_ASSISTANTS_TYPE,
    FOLLOWER_TASKS_TYPE,
    FOLLOWER_GOALS_TYPE,
    FOLLOWER_CONTACTS_TYPE,
    FOLLOWER_NOTES_TYPE,
}
