/**
 * Test utility for simulating webhook callbacks
 * This script helps test the webhook task flow without needing an actual external service
 *
 * Usage:
 *   node testWebhookCallback.js <correlationId> [success|error]
 *
 * Examples:
 *   node testWebhookCallback.js abc-123-def success
 *   node testWebhookCallback.js abc-123-def error
 */

const fetch = require('node-fetch')

// Configuration
const ENVIRONMENT = process.env.WEBHOOK_ENV || 'local' // local | staging | production

const CALLBACK_URLS = {
    local: 'http://localhost:5001/alldonealeph/europe-west1/webhookCallbackForAssistantTasks',
    staging: 'https://europe-west1-alldonestaging.cloudfunctions.net/webhookCallbackForAssistantTasks',
    production: 'https://europe-west1-alldonealeph.cloudfunctions.net/webhookCallbackForAssistantTasks',
}

async function testSuccessCallback(correlationId) {
    const callbackUrl = CALLBACK_URLS[ENVIRONMENT]

    console.log(`🧪 Testing SUCCESS callback to ${ENVIRONMENT} environment`)
    console.log(`   Correlation ID: ${correlationId}`)
    console.log(`   Callback URL: ${callbackUrl}`)

    const payload = {
        correlationId,
        status: 'success',
        resultUrl: 'https://example.com/generated-video-123.mp4',
        metadata: {
            title: 'Test Generated Video',
            duration: '2m 30s',
            fileSize: '45 MB',
            description: 'This is a test video generated by the webhook test utility',
            format: 'mp4',
            resolution: '1920x1080',
        },
    }

    console.log('\n📤 Sending payload:')
    console.log(JSON.stringify(payload, null, 2))

    try {
        const response = await fetch(callbackUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        })

        const responseData = await response.json()

        console.log(`\n📥 Response status: ${response.status}`)
        console.log('Response data:')
        console.log(JSON.stringify(responseData, null, 2))

        if (response.ok) {
            console.log('\n✅ Success callback test completed successfully!')
        } else {
            console.log('\n❌ Success callback test failed')
        }

        return response.ok
    } catch (error) {
        console.error('\n❌ Error sending callback:', error.message)
        return false
    }
}

async function testErrorCallback(correlationId) {
    const callbackUrl = CALLBACK_URLS[ENVIRONMENT]

    console.log(`🧪 Testing ERROR callback to ${ENVIRONMENT} environment`)
    console.log(`   Correlation ID: ${correlationId}`)
    console.log(`   Callback URL: ${callbackUrl}`)

    const payload = {
        correlationId,
        status: 'error',
        error: 'Test error: Video generation failed due to insufficient resources',
    }

    console.log('\n📤 Sending payload:')
    console.log(JSON.stringify(payload, null, 2))

    try {
        const response = await fetch(callbackUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        })

        const responseData = await response.json()

        console.log(`\n📥 Response status: ${response.status}`)
        console.log('Response data:')
        console.log(JSON.stringify(responseData, null, 2))

        if (response.ok) {
            console.log('\n✅ Error callback test completed successfully!')
        } else {
            console.log('\n❌ Error callback test failed')
        }

        return response.ok
    } catch (error) {
        console.error('\n❌ Error sending callback:', error.message)
        return false
    }
}

async function simulateExternalService(correlationId, webhookUrl, prompt) {
    console.log('🌐 SIMULATING EXTERNAL WEBHOOK SERVICE')
    console.log(`   Webhook URL: ${webhookUrl}`)
    console.log(`   Prompt: ${prompt}`)

    // Simulate initial webhook request acknowledgment
    console.log('\n1️⃣  External service receives webhook request...')
    console.log('    ✅ Returning acknowledgment (200 OK)')

    // Simulate processing delay (2 seconds)
    console.log('\n2️⃣  Processing video generation...')
    await new Promise(resolve => setTimeout(resolve, 2000))

    // Simulate successful completion and callback
    console.log('\n3️⃣  Video generation complete! Calling back to Alldone...')
    const success = await testSuccessCallback(correlationId)

    if (success) {
        console.log('\n✅ External service simulation completed successfully!')
    } else {
        console.log('\n❌ External service simulation failed')
    }

    return success
}

// Main execution
async function main() {
    const args = process.argv.slice(2)

    if (args.length < 1) {
        console.log('❌ Usage: node testWebhookCallback.js <correlationId> [success|error|simulate]')
        console.log('\nExamples:')
        console.log('  node testWebhookCallback.js abc-123-def success')
        console.log('  node testWebhookCallback.js abc-123-def error')
        console.log('  node testWebhookCallback.js abc-123-def simulate')
        console.log('\nEnvironment:')
        console.log('  Set WEBHOOK_ENV=local|staging|production (default: local)')
        console.log('  Example: WEBHOOK_ENV=staging node testWebhookCallback.js abc-123-def success')
        process.exit(1)
    }

    const correlationId = args[0]
    const testType = args[1] || 'success'

    console.log('═'.repeat(60))
    console.log('🧪 WEBHOOK CALLBACK TEST UTILITY')
    console.log('═'.repeat(60))
    console.log(`Environment: ${ENVIRONMENT}`)
    console.log(`Test Type: ${testType}`)
    console.log('═'.repeat(60))
    console.log()

    let success = false

    switch (testType.toLowerCase()) {
        case 'success':
            success = await testSuccessCallback(correlationId)
            break
        case 'error':
            success = await testErrorCallback(correlationId)
            break
        case 'simulate':
            success = await simulateExternalService(
                correlationId,
                'https://example.com/api/generate-video',
                'Test video generation'
            )
            break
        default:
            console.log(`❌ Unknown test type: ${testType}`)
            console.log('   Valid types: success, error, simulate')
            process.exit(1)
    }

    console.log('\n' + '═'.repeat(60))
    if (success) {
        console.log('✅ TEST PASSED')
    } else {
        console.log('❌ TEST FAILED')
    }
    console.log('═'.repeat(60))

    process.exit(success ? 0 : 1)
}

// Run if called directly
if (require.main === module) {
    main().catch(error => {
        console.error('❌ Unhandled error:', error)
        process.exit(1)
    })
}

module.exports = {
    testSuccessCallback,
    testErrorCallback,
    simulateExternalService,
}
